[package]
name = "astralfinder"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.10.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
