[package]
name = "demo"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4.9.0"
axum = "0.7.7"
lambda_http = "0.13.0"
lambda_runtime = "0.13.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tokio = "1.41.0"
