[package]
name = "minibell"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
base64 = "0.22.1"
chrono = "0.4.38"
rand = "0.8.5"
serde = { version = "1.0.214", features = ["derive"] }
serde_with = { version = "3.11.0", features = ["chrono"] }
sha2 = "0.10.8"
shaku = "0.6.2"
